title: Prakash Dhungana
description: Embedded Software Engineer · Embedded Linux, RTOS & TinyML
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
logo: /assets/profile/profile_pic_1.png
