title: Prakash Dhungana
logo: /assets/profile/profile_pic.png
description: Ph.D. Student |+ Department of Electrical and Computer Engineering |+ University of Kentucky
show_downloads: true
theme: jekyll-theme-leap-day
